---
#every ansible playbook start with three dashes
-
#this minus in yaml indicate a list of items. the playbook contain a list
#of play with each play as dictionary

#Target: where our play will run
  name: play1
  hosts: worker
  tasks:
    yum:
      name: httpd
      state: started
